// Generated by CoffeeScript 1.4.0
(function() {
  var async, csv2json, logger;

  csv2json = require('../index').csv2json;

  async = require('async');

  logger = require('log4js').getLogger(__filename);

  async.parallel({
    'no fields transform': function(callback) {
      var goodscsv;
      goodscsv = new csv2json('../csv/goods.csv');
      return goodscsv.toJSON({
        decode: 'gbk'
      }, function(err, jsonArr) {
        if (!err && jsonArr) {
          console.log(jsonArr);
        }
        return callback(err);
      });
    },
    'has fields transform': function(callback) {
      var goodscsv;
      goodscsv = new csv2json('../csv/goods.csv');
      return goodscsv.fields({
        '商品Id': 'itemId',
        '名称': 'title',
        '链接': 'link',
        '销量': 'sold',
        '价格': 'price',
        '图片地址': 'picUrl',
        '分类': 'cat'
      }).toJSON({
        headers: true,
        decode: 'gbk'
      }, function(err, jsonArr) {
        if (!err && jsonArr) {
          console.log(jsonArr);
        }
        return callback(err);
      });
    },
    'another fields transform': function(callback) {
      var goodscsv;
      goodscsv = new csv2json('../csv/goods.csv');
      return goodscsv.fields(['itemId', 'title', 'link', 'sold', 'price', 'picUrl', 'cat']).toJSON({
        decode: 'gbk'
      }, function(err, jsonArr) {
        if (!err && jsonArr) {
          console.log(jsonArr);
        }
        return callback(err);
      });
    }
  }, function(err, results) {
    if (err) {
      return logger.error(err);
    } else {
      return logger.info("test end.");
    }
  });

}).call(this);
